### ISSUE TITLE
Command parser

### ISSUE THREAD

**Issue by meew0** [abalabahaha/Dysnomia#1]
Dysnomia should be able to parse input messages and execute the correct module based on the command name and possibly other arguments.

**Comment by hydrabolt** [comment]
I'm on it ;)

**Comment by meew0** [comment]
I think you can assign yourself under "Assignee" on the right. I can't assign anyone apparently (I think I'm not actually a collaborator)

**Comment by hydrabolt** [comment]
Finished parser! ef280d87d859dd4da8406a86217ff4791dc886bf
